version:  '3.8'
services:
    nginx:
      build:
        context: Dockers/nginx
        dockerfile: Dockerfile
        args:
          - APP_ENV=prod
      image: php:8.2.11-zts-alpine3.18
      ports:
        - "80:80"
      container_name: my-app