version:  '3.8'
services:
    nginx:
      build:
        context: Dockers/nginx
        dockerfile: Dockerfile
        args:
          - APP_ENV=prod
      image: sysadm:symfony-locale-demo
      ports:
        - "80:80"
      container_name: my-app